spring.application.name=clipperBarberShop
spring.datasource.url=jdbc:postgresql://localhost:5432/clipperdb
spring.datasource.username=clipper
spring.datasource.password=clipper123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect